services:
  - type: web
    name: asistencia-django
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn asistencia.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: asistencia.settings
      - key: PYTHON_VERSION
        value: 3.10

